language: java

sudo: false

jdk:
  - oraclejdk8

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
    - GSOC_2017_kafka

before_install: 
  - "npm install -g grunt-cli bower@1.3.9"

script: "mvn verify javadoc:jar"
