language: java

jdk:
  - oraclejdk7
  - openjdk6

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
    - 1.0.x

before_install: "npm install -g grunt-cli bower@1.3.8"

script: "mvn verify -X"
